name: Shulkerd
main: io.github.joshy56.Shulkerd
version: 1
api-version: 1.19
permissions:
  shulkerd.*:
    description: Gives all permissions of Shulkerd.
    default: false
    children:
      shulkerd.use: true
  shulkerd.use:
    description: Allows to open a shulker box without place it on the ground.
    default: false